import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "./(routes)/register/context/auth.context";
import { PrimeReactProvider } from "primereact/api";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.className} antialiased`}>
        <AuthProvider>
          <PrimeReactProvider>{children}</PrimeReactProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
