import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "./(routes)/register/context/auth.context";
import { ServerProvider } from "./(routes)/home/context/server.context";
import { UserProvider } from "./(routes)/home/context/user.context";
import { ChannelProvider } from "./(routes)/home/(routes)/[id]/context/channel.context";
import { PrimeReactProvider } from "primereact/api";
import { EventProvider } from "./(routes)/home/(routes)/[id]/context/event.context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.className} antialiased`}>
        <AuthProvider>
          <PrimeReactProvider>
            <ServerProvider>
              <UserProvider>
                <ChannelProvider>
                  <EventProvider>{children}</EventProvider>
                </ChannelProvider>
              </UserProvider>
            </ServerProvider>
          </PrimeReactProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
